# Generated by Django 5.0.6 on 2024-06-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_remove_transport_transport_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transport',
            old_name='revenue',
            new_name='costs',
        ),
    ]
