# Generated by Django 5.0.6 on 2024-06-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_rename_revenue_transport_costs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cost',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='route',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='transport',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='route',
            name='fare',
        ),
        migrations.AddField(
            model_name='transport',
            name='fare',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
