# Generated by Django 5.0.6 on 2024-06-02 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0004_alter_cost_options_alter_route_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forecast',
            name='profitability',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
