# Generated by Django 5.0.6 on 2024-06-02 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0005_forecast_profitability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='transport',
            new_name='transport_id',
        ),
    ]
