# Generated by Django 5.0.6 on 2024-06-02 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0006_rename_transport_forecast_transport_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='profitability',
            new_name='predicted_profitability',
        ),
    ]
