# Generated by Django 5.0.6 on 2024-06-06 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0007_rename_profitability_forecast_predicted_profitability'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cost',
        ),
    ]
